### ISSUE TITLE
[Issue] Settings app won't close when importing custom wallpaper or settings files

### ISSUE THREAD

**Issue by Notplayingallday383** [TerbiumOS/webOS#36] opened 2023-05-09 12:31 UTC
Hi, Recently on terbium I added a custom picture as the wallpaper and after testing it on multiple versions of terbium that support this its the same thing where you can close the app its just stuck on the screen and I was wondering if it could be fixed

**Comment by Notplayingallday383** [comment] 2023-05-09 21:13
Update: This issue is also present with most file dialogs

**Comment by NovaAppsInc** [comment] 2023-05-31 10:24
it might be a lag or Terbium shitting itself; I believe this is the cause because when I added custom image from local system it started lagging my system but I never looked into it deeper as it could be fixed with refreshing.

But if you still experience this please show me if you can and the console log.

P.S. Once I get the VPS paid you should be able to get back on lol

**Comment by Notplayingallday383** [comment] 2023-05-31 10:39
Alr

**Closed** 2023-10-07 23:59 UTC
